name: nals_lints
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  analyzer: 7.4.5
  build_resolvers: 2.4.4
  custom_lint_builder: 0.7.5
  hotreloader: 4.3.0
  source_gen: 2.0.0
  vm_service: 15.0.2
